services:
  # price-db:
  #   image: redis:7.4.2
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - pricedb_data:/data
  #   command: ["redis-server", "--appendonly", "yes"]
  #   restart: always

  price-monitor:
    container_name: price-monitor
    restart: always
    build:
      context: ./src/price-monitor
    command:
      - python
      - main.py
      - --config
      - config/config-arbitrum.yaml
    volumes:
      - ./src/price-monitor/config:/app/config
    ports:
      - "8080:8080"

  dex-arbitrage:
    container_name: dex-arbitrage
    restart: always
    build:
      context: ./src/dex-arbitrage
    command:
      - python
      - main.py
      - --config
      - config/config-arbitrum.yaml
    volumes:
      - ./src/dex-arbitrage/config:/app/config

volumes:
  pricedb_data:
    driver: local
