rpc_url: https://arbitrum-mainnet.core.chainstack.com/8c5b804a71a219985230ebee411964ad
network_name: Arbitrum
monitor_period_ms: 50
api:
  server_host: 0.0.0.0
  server_port: 8080
price_db:
  enable: false
  redis_host: price-db
  redis_port: 6379
exchanges:
  uniswap-v2:
    pair_abi_file: uniswap-v2-pool.json
    pairs:
      ETH/USDC:
        address: "0xF64Dfe17C8b87F012FCf50FbDA1D62bfA148366a"
        token0_decimals: 18
        token1_decimals: 6
  uniswap-v3:
    pair_abi_file: uniswap-v3-pool.json
    pairs:
      ETH/USDC:
        address: "0xC6962004f452bE9203591991D15f6b388e09E8D0"
        token0_decimals: 18
        token1_decimals: 6
  # sushiswap-v3:
  #   pair_abi_file: 
  #   pairs:
  #     ETH/USDC:
  #       address: "0x8f46184f825449de62cb022952E6Ad6D15d357c9"
  #       token0_decimals: 6
  #       token1_decimals: 6
  # curve:
  #   pair_abi_file: 
  #   pairs:
  #     ETH/USDC:
  #       address: ""
  #       token0_decimals: 6
  #       token1_decimals: 6
