rpc_url: https://arbitrum-mainnet.core.chainstack.com/8c5b804a71a219985230ebee411964ad
network_name: Arbitrum
price_query:
  type: "http"
  period_ms: 50
monitor:
  url: "http://price-monitor:8080"
price_db:
  redis_host: price-db
  redis_port: 6379